# Generated by Django 4.2.5 on 2023-11-01 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Students', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppStudents',
            new_name='Student',
        ),
    ]
